version: "3.9"
services:
  laminas_app:
    container_name: laminas_app
    build: .
    ports:
     - "8080:80"
    volumes:
     - .:/var/www
    links:
      - laminas_redis
      - laminas_mysql
    environment:
      - REDIS_URL=redis://cache
    depends_on:
      - laminas_mysql
      - laminas_redis

  laminas_redis:
    image: redis
    container_name: laminas_redis
    ports:
      - "13598:6379"

  laminas_mysql:
    image: mysql
    container_name: laminas_mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1'
      MYSQL_DATABASE: 'laminas'
    ports:
      - "3320:3306"